- name: Put SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive


- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled


- name: add active ports
  firewalld:
    port: '{{item}}'
    permanent: true
    state: enabled
  with_items:
    - {{openvpn_port}}/udp


- name: core modification
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1
    create: yes

- name: enabling masquarade for nat
  ansible.posix.firewalld:
    zone: public
    masquarade: enable
    permanent: yes
