#! /bin/bash

#GCSFUSE

if ! [ -x "$(command -v gcfuse)" ]; then
  echo 'Error GCSFUSE is not installed'

  #Adding repository of GCSFUSE

  export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
  echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

  #updating repository and installing gcsfuse

  sudo apt update
  sudo apt install gcsfuse

else
  echo 'OK GCSFUSE is installed'
  exit 1
fi

#Mounting bucket to VM
1

