#install all dependencies for correct work of wordpress
- name: upgrade system
  apt:
    upgrade: yes
    update_cache: 'true'
  become: true

- name: installing all dependencies
  apt:
    name:
    - php
    - php-curl
    - php-common
    - php-mbstring
    - php-gd
    - php-intl
    - php-xml
    - php-mysql
    - php-fpm
    - php-zip
    - apache2
    - unzip
    state: present
  become: true

- name: upload script for installing gcsfuse
  ansible.builtin.copy:
    src: ../files/install-gcsfuse.sh
    dest: /tmp/gcsfuse-install.sh
    owner: pfaka
    mode: '0755'
  become: true

- name: run script for installing gcsfuse
  shell: /tmp/gcsfuse-install.sh

# Enabling rewrite mode for apache2

- name: Enable rewrite module
  apache2_module:
    name: rewrite
    state: present
  become: true

#Change config for apache2 default-site

- name: upload config for apache default site
  ansible.builtin.copy:
    src: ../files/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    owner: pfaka
    mode: '0644'
  become: true

#Change config for upload dir

- name: upload config for apache dir.conf
  ansible.builtin.copy:
    src: ../files/dir.conf
    dest: /etc/apache2/mods-enabled/dir.conf
    owner: pfaka
    mode: '0644'
  become: true

#Enable apache2 service for normally work

- name: enable apache
  service:
    name: apache2
    enabled: yes
  become: true

#Change fuse.conf file for enable "allow_other" attribute

- name: upload fuse.conf
  ansible.builtin.copy:
    src: ../files/fuse.conf
    dest: /etc/fuse.conf
    owner: pfaka
    mode: '0644'
  become: true
