#install all dependencies for correct work of wordpress

- name: exporting repo for installing gcsfuse
  ansible.builtin.command:
      - export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
      - echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
      - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  become: true

- name: upgrade system
  apt:
    upgrade: yes, dist
    update_cache: true
  become: true


- name: installing all dependencies
  apt:
    name:
    - php
    - php-curl
    - php-common
    - php-mbstring
    - php-gd
    - php-intl
    - php-xml
    - php-mysql
    - php-fpm
    - php-zip
    - apache2
    - unzip
    - gcsfuse
  state: present
  become: true


#Enable apache2 service for normally work

- name: enable apache
  service:
    name: apache2
    enabled: yes
  become: true

#Change config for apache2 default-site

- name: upload config for apache default site
  ansible.builtin.copy:
    src: /ansible/roles/wordpress/files/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    owner: pfaka
    mode: '0644'
  become: true

#Change config for upload dir

- name: upload config for apache dir.conf
  ansible.builtin.copy:
    src: /ansible/roles/wp-deploy/files/dir.conf
    dest: /etc/apache2/mods-enabled/dir.conf
    owner: pfaka
    mode: '0644'
  become: true

# Enabling rewrite mode for apache2

- name: Enable rewrite module
  apache2_module:
    name: rewrite
    state: present
  become: true

#Change fuse.conf file for enable "allow_other" attribute

- name: upload fuse.conf
  ansible.builtin.copy:
    src: /ansible/roles/wp-deploy/files/fuse.conf
    dest: /etc/fuse.conf
    owner: pfaka
    mode: '0644'
  become: true

- name: creating symlink
  command: ln -s ../../mnt ../../var/www
  become: true